export const SET_SESSION = 'SET_SESSION';
export const SET_SESSION_ROLES = 'SET_SESSION_ROLES';
export const SET_SESSION_ARTISTA = 'SET_SESSION_ARTISTA';
export const SET_SESSION_USER_MESSAGE = 'SET_SESSION_USER_MESSAGE';
export const SET_SESSION_USER = 'SET_SESSION_USER';
