export * from './contact-form';
export * from './footer';
export * from './header__nav';
export * from './header';
export * from './info-card';
export * from './palabras-del-equipo';
export * from './simple-text';
export * from './social-icons';
export * from './testimonio';